trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
    - bash: echo $(PipelineLevelVAriable)
  - job: SecondtJob
    steps:
    - bash: echo Build SecondJob
- stage: Dev_Deploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo Build $(environment) DeployJob

- stage: QA_Deploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo Build QADeployJob

- stage: Prod_Deploy
  dependsOn:
  - Dev_Deploy
  - QA_Deploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Build prod DeployJob

