trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondtJob
    steps:
    - bash: echo Build SecondJob
- stage: Dev_Deploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo Build DevDeployJob

- stage: QA_Deploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo Build QADeployJob

- stage: Prod_Deploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Build prod DeployJob

